version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    command: python main.py
    volumes:
      - ./server:/app
    ports:
      - 8000:8000

  client:
    image: react
    container_name: react-client
    ports:
      - '3000:3000'

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: